---
title: "lsqlthw04"
author: "Robert A. Stevens"
date: "March 23, 2016"
output: html_document
---

http://sql.learncodethehardway.org/book/

# Learn SQL The Hard Way

http://sql.learncodethehardway.org/book/ex4.html

## Exercise 4: Insert Referential Data

In the last exercise you filled in some tables with people and pets. The only thing that's missing is who owns what pets, and that data goes into the person_pet table like this:

    INSERT INTO person_pet (person_id, pet_id) VALUES (0, 0);
    INSERT INTO person_pet VALUES (0, 1);

Again I'm using the explicit format first, then the implicit format. How this works is I'm using the id values from the person row I want (in this case, 0) and the id from the pet rows I want (again, 0 for the Unicorn and 1 for the Dead Robot). I then insert one row into person_pet relation table for each "connection" between a person and a pet.

## What You Should See

I'll just piggyback on the last exercise and run this right on the ex3.db database to set these values:

    $ sqlite3 -echo ex3.db < ex4.sql
    INSERT INTO person_pet (person_id, pet_id) VALUES (0, 0);
    INSERT INTO person_pet VALUES (0, 1);
    $

```{r comment=NA}
library(sqldf)
# repeat from Exercise # 2
sqldf("attach 'ex2' as new")
sqldf("CREATE TABLE person (
           id INTEGER PRIMARY KEY,
           first_name TEXT,
           last_name TEXT,
           age INTEGER
       );", dbname = "ex2")
sqldf("CREATE TABLE person_pet (
           person_Id INTEGER,
           pet_Id INTEGER
       );", dbname = "ex2")
sqldf("CREATE TABLE pet (
           id INTEGER PRIMARY KEY,
           name TEXT,
           breed TEXT,
           age INTEGER,
           dead INTEGER
       );", dbname = "ex2")
# new for Exercise # 3
sqldf("INSERT INTO person (id, first_name, last_name, age) 
           VALUES (0, 'Zed', 'Shaw', 37);", dbname = "ex2")
sqldf("INSERT INTO pet (id, name, breed, age, dead)
           VALUES (0, 'Fluffy', 'Unicorn', 1000, 0);", dbname = "ex2")
sqldf("INSERT INTO pet VALUES (1, 'Gigantor', 'Robot', 1, 1);", dbname = "ex2")
# new for Exercise # 4
sqldf("INSERT INTO person_pet (person_id, pet_id) VALUES (0, 0);", dbname = "ex2")
sqldf("INSERT INTO person_pet VALUES (0, 1);", dbname = "ex2")
# repeat from Exercise # 2
sqldf("select * from person", dbname = "ex2")
sqldf("select * from person_pet", dbname = "ex2")
sqldf("select * from pet", dbname = "ex2")
```

## Extra Credit

- Add the relationships for you and your pets.

- Using this table, could a pet be owned by more than one person? Is that logically possible? What about the family dog? Wouldn't everyone in the family technically own it?

- Given the above, and given that you have an alternative design that puts the pet_id in the person table, which design is better for this situation?
