---
title: "lsqlthw05"
author: "Robert A. Stevens"
date: "March 23, 2016"
output: html_document
---

http://sql.learncodethehardway.org/book/

# Learn SQL The Hard Way

http://sql.learncodethehardway.org/book/ex5.html

## Exercise 5: Selecting Data

Out of the CRUD matrix you only know "Create". You can create tables and you can create rows in those tables. I'll now show you how to "Read" or in the case of SQL, SELECT: 
    
    SELECT * FROM person;
    
    SELECT name, age FROM pet;
    
    SELECT name, age FROM pet WHERE dead = 0;
    
    SELECT * FROM person WHERE first_name != "Zed";

Here's what each of these lines does:

### ex5.sql:1

This says "select all columns from person and return all rows." The format for SELECT is SELECT what FROM tables(s) WHERE (tests) and the WHERE clause is optional. The '*' (asterisk) character is what says you want all columns.

### ex5.sql:3

In this one I'm only asking for two columns name and age from the pet table. It will return all rows.

### ex5.sql:5

Now I'm looking for the same columns from the pet table but I'm asking for only the rows where dead = 0. This gives me all the pets that are alive.

### ex5.sql:7

Finally I'm selecting all columns from person just like in the first line, but now I'm saying only if they do not equal "Zed". That WHERE clause is what determines which rows to return or not.

## What You Should See

When you run this with sqlite3 -echo you should get something like the following output:

    $ sqlite3 -echo ex3.db < ex5.sql
    SELECT * FROM person;
    0|Zed|Shaw|37
    SELECT name, age FROM pet;
    Fluffy|1000
    Gigantor|1
    SELECT name, age FROM pet WHERE dead = 0;
    Fluffy|1000
    SELECT * FROM person WHERE first_name != "Zed";
    $

```{r comment=NA}
library(sqldf)

# repeat from Exercise # 2
sqldf("attach 'ex2' as new")
sqldf("CREATE TABLE person (
           id INTEGER PRIMARY KEY,
           first_name TEXT,
           last_name TEXT,
           age INTEGER
       );", dbname = "ex2")
sqldf("CREATE TABLE person_pet (
           person_Id INTEGER,
           pet_Id INTEGER
       );", dbname = "ex2")
sqldf("CREATE TABLE pet (
           id INTEGER PRIMARY KEY,
           name TEXT,
           breed TEXT,
           age INTEGER,
           dead INTEGER
       );", dbname = "ex2")

# repeat from Exercise # 3
sqldf("INSERT INTO person (id, first_name, last_name, age) 
           VALUES (0, 'Zed', 'Shaw', 37);", dbname = "ex2")
sqldf("INSERT INTO pet (id, name, breed, age, dead)
           VALUES (0, 'Fluffy', 'Unicorn', 1000, 0);", dbname = "ex2")
sqldf("INSERT INTO pet VALUES (1, 'Gigantor', 'Robot', 1, 1);", dbname = "ex2")

# repeat from Exercise # 4
sqldf("INSERT INTO person_pet (person_id, pet_id) VALUES (0, 0);", dbname = "ex2")
sqldf("INSERT INTO person_pet VALUES (0, 1);", dbname = "ex2")

# new for Exercise # 5
sqldf("SELECT * FROM person;", dbname = "ex2")
sqldf("SELECT name, age FROM pet;", dbname = "ex2")
sqldf("SELECT name, age FROM pet WHERE dead = 0;", dbname = "ex2")
sqldf("SELECT * FROM person WHERE first_name != 'Zed';", dbname = "ex2")
```

I say "something like" because if you were doing the extra credit this whole time you will have different rows in your database. For example, if you added yourself then you will have some rows listed at the end. In my example above I have nothing returned for the last query because I'm the only person in the person table, and that means no row match the last query's WHERE clause. Study this carefully.

## Extra Credit

- Write a query that finds all pets older than 10 years.

- Write a query to find all people younger than you. Do one that's older.

- Write a query that uses more than one test in the WHERE clause using the AND to write it. For example, WHERE first_name = "Zed" AND age > 30.

- Do another query that searches for rows using 3 columns and uses both AND and OR operators.

## Portability Notes

Some databases have additional operators and boolean logic tests, but just stick to the regular ones that you find in most programming languages for now.
